# Generated by Django 3.0.5 on 2020-04-26 15:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Ativo?')),
                ('first_name', models.CharField(db_index=True, max_length=30, unique=True, verbose_name='Nome')),
                ('last_name', models.CharField(db_index=True, max_length=30, unique=True, verbose_name='Nome')),
                ('email', models.CharField(db_index=True, max_length=30, unique=True, verbose_name='Nome')),
                ('document', models.CharField(db_index=True, max_length=30, unique=True, verbose_name='Nome')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Customers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
    ]
