# Generated by Django 3.0.5 on 2020-04-26 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='category_products', to='products.Category', verbose_name='Categoria'),
            preserve_default=False,
        ),
    ]
